build:
	gcc client.c ../../btclient.c ../../gameloop.c ../../vec.c ../../log.c ../../ansicode.c -Wall -Wextra -g3 -Og -o client -lbluetooth
	gcc server.c ../../btserver.c ../../btclient.c ../../vec.c ../../log.c ../../ansicode.c -Wall -Wextra -g3 -Og -o server -lbluetooth

