build: 
	gcc client.c ../../tcpclient.c ../../log.c ../../ansicode.c ../../gameloop.c ../../vec.c -I../.. -Wall -Wextra -g3 -Og -o client
	gcc server.c ../../tcpclient.c ../../log.c ../../ansicode.c ../../gameloop.c ../../vec.c ../../tcpserver.c -I../.. -Wall -Wextra -g3 -Og -o server
